image:
  file: .gitpod.dockerfile

ports:
- port: 8080
  onOpen: open-preview

tasks:
# show helpful hints in console
- name: Terminal
  command: >
    echo "";
    echo "Commands you can try:";
    echo " * apachectl stop";
    echo " * apachectl start";
    echo " * gp open /var/log/apache2/access.log";
    echo " * gp open /var/log/apache2/error.log";
# configure and start web server
- name: Apache
  command: >
    cp apache.conf /etc/apache2/apache2.conf;
    apachectl start &&
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log;
    gp await-port 8001 && gp preview $(gp url 8001)

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
